### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [vbresan/MindfulnessMeditation#1]
With your app now available at F-Droid.org, do you wish to keep it listed at IzzyOnDroid? I see no badge for it in the Readme, so I wonder…

**Comment by vbresan** [comment]
I wasn't aware it's there. Yes, I want to keep it listed, I have added the badge in the Readme.

**Comment by IzzySoft** [comment]
Thanks! Marked for "keep" then :smiley:
