### ISSUE TITLE
Mistake in "Body Scan" audio

### ISSUE THREAD

**Issue by randomguy3** [vbresan/MindfulnessMeditation#2]
In the Body Scan audio, at 10:03, there's a mistake where Dr Crane says "So now holding the both", then pauses, then starts this section again. I assume the intention was to edit that part out, and it just got forgotten about.

The edit is easy enough to make in something like Audacity - I would suggest removing from 10:02.4 to 10:06.3 (which removes some of the surrounding noises, and connects two very similar bits of background noise together).

**Comment by vbresan** [comment]
Thank you for your suggestion, but the meditations are provided as-is and modifications are not allowed.
